#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# openvela AI Contest - collector install script
#
# Install the collector into a contestant demo repo (either generated by
# npx create-vela-workflow or any other track's project). Idempotent, safe to re-run.
#
# Usage:
#   bash install.sh [--team-id contest2026-NNN-form]
#
# Must be executed at the contestant demo repo root.
# TEAM_ID is required (CLI flag takes priority, env var as fallback).

set -eu

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --team-id <id>    Team identifier (e.g. team-099-yanxingyu).
                    Falls back to \$TEAM_ID env var.
  -h, --help        Show this help.

This script installs:
  .opencode/plugins/contest-collector.js   (OpenCode plugin)
  .claude/hooks/contest-snapshot.sh        (Claude Code hook)
  .claude/shared/snapshot_core.py          (shared core)
  .claude/contest-settings.snippet.json    (settings snippet for user to merge)
  .gitignore                               (adds logs/.last_push, logs/.cache)

It does NOT install:
  ~/.codex/hooks/                          (user-global, not project-local)
  .kiro/hooks/                             (Kiro adapter not yet implemented)

After running, follow the printed next-steps to:
  1. Merge contest-settings.snippet.json into your .claude/settings.json
  2. Set TEAM_ID env var (or .env)
  3. (Codex users only) Run /hooks → trust inside Codex CLI once
EOF
}

TEAM_ID_OVERRIDE=""
GITHUB_LOGIN_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --team-id) TEAM_ID_OVERRIDE="$2"; shift 2 ;;
    --github-login) GITHUB_LOGIN_OVERRIDE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

TEAM_ID_FINAL="${TEAM_ID_OVERRIDE:-${TEAM_ID:-}}"
if [ -z "$TEAM_ID_FINAL" ]; then
  echo "❌ FATAL: TEAM_ID not set. Pass --team-id contest2026-NNN or export TEAM_ID." >&2
  exit 2
fi

if ! echo "$TEAM_ID_FINAL" | grep -qE '^[a-zA-Z][a-zA-Z0-9_-]+$'; then
  echo "❌ FATAL: TEAM_ID '$TEAM_ID_FINAL' must start with a letter and contain only [a-zA-Z0-9_-]" >&2
  exit 2
fi

if [ ! -d .git ]; then
  echo "❌ FATAL: not in a git repository. cd to your demo repo root first." >&2
  exit 2
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ ! -f "$SOURCE_ROOT/adapters/opencode/collector.js" ]; then
  echo "❌ FATAL: cannot locate adapters/. SOURCE_ROOT=$SOURCE_ROOT" >&2
  echo "   Run install.sh from the contest-log-upload/onboarding/ directory." >&2
  exit 2
fi

if [ -n "$GITHUB_LOGIN_OVERRIDE" ]; then
  GITHUB_LOGIN_FINAL="$GITHUB_LOGIN_OVERRIDE"
  GITHUB_LOGIN_SOURCE="cli-arg"
else
  DETECT_OUT=$(GITHUB_LOGIN="${GITHUB_LOGIN:-}" python3 "$SOURCE_ROOT/adapters/shared/get_github_login.py" "$REPO_ROOT" 2>&1) || DETECT_OUT=""
  GITHUB_LOGIN_FINAL=$(echo "$DETECT_OUT" | awk -F'\t' '{print $1}')
  GITHUB_LOGIN_SOURCE=$(echo "$DETECT_OUT" | awk -F'\t' '{print $2}')
fi

if [ -z "$GITHUB_LOGIN_FINAL" ] || ! echo "$GITHUB_LOGIN_FINAL" | grep -qE '^[A-Za-z0-9][A-Za-z0-9-]{0,38}$'; then
  echo "❌ FATAL: cannot determine GitHub username." >&2
  echo "   Try one of:" >&2
  echo "     1. gh auth login" >&2
  echo "     2. bash install.sh --github-login your-github-name --team-id $TEAM_ID_FINAL" >&2
  echo "     3. export GITHUB_LOGIN=your-github-name && bash install.sh --team-id $TEAM_ID_FINAL" >&2
  exit 2
fi

echo "📦 Installing contest collector (machine-wide, zero touch on demo repo)"
echo "   TEAM_ID:      $TEAM_ID_FINAL"
echo "   GITHUB_LOGIN: $GITHUB_LOGIN_FINAL  (source: $GITHUB_LOGIN_SOURCE)"
echo "   Demo repo:    $REPO_ROOT  (untouched)"
echo ""

if ! python3 -c "import jsonschema" 2>/dev/null; then
  if pip3 install --quiet --user jsonschema 2>/dev/null; then
    echo "✅ pip install jsonschema (required by validate-log.py)"
  else
    echo "⚠️  python3 -m pip install jsonschema  failed; install it manually before running validate-log.py"
  fi
else
  echo "✓  python3 jsonschema already installed"
fi

USER_CLAUDE_DIR="${HOME}/.claude"
USER_CONTEST_DIR="$USER_CLAUDE_DIR/contest-shared"
USER_STAGING_DIR="$USER_CLAUDE_DIR/contest-collector-staging"
USER_GLOBAL_ENV="$USER_CLAUDE_DIR/contest-collector.env"
USER_OPENCODE_DIR="${HOME}/.config/opencode/plugin"
mkdir -p "$USER_CLAUDE_DIR" "$USER_CONTEST_DIR" "$USER_STAGING_DIR" "$USER_OPENCODE_DIR"

if [ ! -f "$USER_GLOBAL_ENV" ]; then
  cat > "$USER_GLOBAL_ENV" <<EOF
TEAM_ID=$TEAM_ID_FINAL
GITHUB_LOGIN=$GITHUB_LOGIN_FINAL
EOF
  echo "✅ ~/.claude/contest-collector.env (your contest identity, machine-wide)"
else
  echo "✓  ~/.claude/contest-collector.env already exists, leaving it alone"
fi

cp "$SOURCE_ROOT/adapters/shared/snapshot_core.py" "$USER_CONTEST_DIR/snapshot_core.py"
cp "$SOURCE_ROOT/adapters/shared/get_github_login.py" "$USER_CONTEST_DIR/get_github_login.py"

cat > "$USER_CONTEST_DIR/contest-snapshot.sh" <<'GLOBAL_HOOK_EOF'
#!/usr/bin/env bash
set -eu

GLOBAL_ENV="$HOME/.claude/contest-collector.env"
[ -f "$GLOBAL_ENV" ] || exit 0

set -a
. "$GLOBAL_ENV"
set +a

[ -z "${TEAM_ID:-}" ] && exit 0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec python3 "$SCRIPT_DIR/snapshot_core.py" --tool claude-code
GLOBAL_HOOK_EOF
chmod +x "$USER_CONTEST_DIR/contest-snapshot.sh"
echo "✅ ~/.claude/contest-shared/ (Claude Code + Codex global hook)"

cp "$SOURCE_ROOT/adapters/opencode/collector.js" "$USER_OPENCODE_DIR/contest-collector.js"
echo "✅ ~/.config/opencode/plugin/contest-collector.js (OpenCode global plugin)"

USER_SETTINGS="$USER_CLAUDE_DIR/settings.json"
GLOBAL_HOOK_CMD="bash $USER_CONTEST_DIR/contest-snapshot.sh"

python3 - "$USER_SETTINGS" "$GLOBAL_HOOK_CMD" <<'MERGE_PY'
import json, sys, os
path, cmd = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(path):
    with open(path) as f:
        try:
            data = json.load(f)
        except Exception:
            print(f"⚠️  {path} exists but is not valid JSON; backing up and re-creating")
            os.rename(path, path + ".contest-backup")
            data = {}
hooks = data.setdefault("hooks", {})
contest_marker = "contest-shared/contest-snapshot.sh"
for event in ("Stop", "SessionEnd"):
    arr = hooks.setdefault(event, [])
    if any(contest_marker in str(h) for group in arr for h in group.get("hooks", [])):
        continue
    arr.append({"hooks": [{"type": "command", "command": cmd, "timeout": 30}]})
with open(path, "w") as f:
    json.dump(data, f, indent=2)
print(f"✅ {path} (Stop+SessionEnd registered for Claude Code)")
MERGE_PY

TOOLS_REL="../.claude/skills/contest-log-collector/tools"

USER_BIN_DIR="${HOME}/.local/bin"
USER_SHORTCUT="$USER_BIN_DIR/contest-snapshot"
mkdir -p "$USER_BIN_DIR"

cat > "$USER_SHORTCUT" <<'SHORTCUT_EOF'
#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# openvela AI Contest - export-session.py shortcut.
# Resolves the export-session.py script via 'git rev-parse --show-toplevel'
# of the current working directory, then walks one level up to find the
# sibling .claude/ tools repo. Forwards all args verbatim.
set -eu

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$REPO_ROOT" ]; then
  echo "❌ contest-snapshot must be run from inside your demo repo" >&2
  exit 2
fi

EXPORT_PY="$REPO_ROOT/../.claude/skills/contest-log-collector/tools/export-session.py"
if [ ! -f "$EXPORT_PY" ]; then
  echo "❌ cannot locate export-session.py at $EXPORT_PY" >&2
  echo "   Did 'repo sync' pull the .claude tools repo as a sibling?" >&2
  exit 2
fi

exec python3 "$EXPORT_PY" "$@"
SHORTCUT_EOF
chmod +x "$USER_SHORTCUT"
echo "✅ $USER_SHORTCUT (short command: contest-snapshot)"

case ":$PATH:" in
  *":$USER_BIN_DIR:"*)
    ;;
  *)
    echo "⚠️  $USER_BIN_DIR is NOT in your PATH"
    echo "   To use the 'contest-snapshot' short command, add it once:"
    echo "     echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
    echo "     (or your shell's equivalent rc file)"
    ;;
esac

echo ""
echo "─────────────────────────────────────────────────────"
echo "📋 NEXT STEPS"
echo "─────────────────────────────────────────────────────"
echo ""
echo "1. Verify the install (one-time):"
echo "   bash $SOURCE_ROOT/onboarding/verify-setup.sh"
echo ""
echo "2. Start working with AI, inside the openvela workspace."
echo "   The collector only activates when you are inside an openvela"
echo "   workspace (a parent dir contains .repo/). Sessions in personal"
echo "   projects elsewhere are NOT collected at all."
echo ""
echo "3. Sessions are auto-written into logs/<github_login>/ when they end."
echo "   You do not need to run any command for the normal flow. The tool"
echo "   only writes files - it never git commits or pushes."
echo ""
echo "4. Commit the new files under logs/<github_login>/ together with your code:"
echo "     git add logs/ && git commit -s -m 'logs: capture session' && git push"
echo ""
echo "   (Optional) To list or re-export a session manually:"
echo "     contest-snapshot --list"
echo "     contest-snapshot --session <id> --confirm"
echo "   Or full path: python3 $TOOLS_REL/export-session.py --list"
echo ""
